@startuml

//www.plantuml.com/plantuml/png/ZLLDRniX4Btlh-3egBwaLrTHxBYH8bcLPRkzL3rWcAvHM5Z1uAID-jyBYtU3MIpdmffvRpxWpU1xYzIWQsJ59BMMCAqG53xuZz5IWY6YQIKqtcR9an8eg1H_wLx2oU6W6tXddun8xVC6Vfzsbe4gSFHIpzjM2aPHQ5LTAg1wgpwrHXmf0bauHAq8azh2xDtyrD0QZW9UY4LeRyFMmnvtUn-U7BNWHFIrm-JxPaMSaLEo0QkTOR1mYaiWPdzpvXFpn9oJEGjLVZtwsWY4zQRwLoLtK2YJSZuRrsx0xyPsVytQODoCKGuI4BP-PGZy4ZwNSWp1QmWyjdlXqTbPbGCBQWXgBVqtSTh1ApuAaBpJzXjjeDjTPAo4nPonzCjQi6SmX3i8kvonedkGWt_8ajQt2stt8yZyPGt6QdNNKJlpBACzQEaQTU9DoHQDKFNTKBo7F-WHA-qSFkWHBzQ3UGj6wNU-X4dMQ9JpWZbJVUti0NZEYTdAsD0LPJXsHXcBxHXKo95Qx_paCbkQY4iJ5sSbVHhISTbsJqoylhNHBHZyCoWrkyAB-boZfTqUIuogJI9jo3Ob95hwkBsifm1aE6Dlhm6t7JGIPW3EGvGYB6EoSOW1EQ-g5EDHc3WoeoWfbfrt50Xr_14bAx_VgNH8Qo0shAa2mI6w9TOrDQ5LZDQOJuPz4SWEEzqvtbxfh8p-kVmqN_YNUHjDZy59SeeXKwTMJskew5lbvoz2JMr3YdjGt3NoFm00

class contentController implements Initializable
class homeController
class taskRef
class sceneController
class toDoApplication

class contentController
{
+private Button close;
+private Imageview step1Image;

+public void initialize(URL url, ResourceBundle rb)
+public void closeButton(ActionEvent event)
}

class home
{
+private Button add;
+private Button create;
+private Button importButton;
+private Button deleteSelected;
+private Button deleteAll;
+private Button export;
+private Button status;

+private ButtonBar toolBar;
+private TextField taskNameField;
+private TextField taskListField;
+private DatePicker dueDateField;
+private Label taskListName;

+private TableView <Person> taskTable;
+private TableColumn<Person, String> taskNameCol;
+private TableColumn<Person, String> dueDateCol;;
+private TableColumn<Person, String> statusCol;

+public void createTask()
+public void addTask()
+public void deleteSelectedPushed()
+public void statusPushed()
+public void deleteAllPushed()
+public void exportPushed()
+public void importList()
+public void goToDocs(ActionEvent event)
+public void initialize()
}

class taskRef
{
+private SimpleStringProperty taskName;
+private SimpleStringProperty dueDate;
+private SimpleStringProperty status;

+public Person(String taskName,  String dueDate, String status )
+public String getStatus()
+public void setStatus( String status)
+public String getDueDate()
+public void setDueDate(String dueDate)
+public String getFirstName()
+public void setFirstName(String taskName)
+public String toString()
}

class sceneController
{
+private Sclass contentController implements Initializable
          class homeController
          class taskRef
          class sceneController
          class toDoApplication

          class contentController
          {
          +private Button close;
          +private Imageview step1Image;

          +public void initialize(URL url, ResourceBundle rb)
          +public void closeButton(ActionEvent event)
          }

          class home
          {
          +private Button add;
          +private Button create;
          +private Button importButton;
          +private Button deleteSelected;
          +private Button deleteAll;
          +private Button export;
          +private Button status;

          +private ButtonBar toolBar;
          +private TextField taskNameField;
          +private TextField taskListField;
          +private DatePicker dueDateField;
          +private Label taskListName;

          +private TableView <Person> taskTable;
          +private TableColumn<Person, String> taskNameCol;
          +private TableColumn<Person, String> dueDateCol;;
          +private TableColumn<Person, String> statusCol;

          +public void createTask()
          +public void addTask()
          +public void deleteSelectedPushed()
          +public void statusPushed()
          +public void deleteAllPushed()
          +public void exportPushed()
          +public void importList()
          +public void goToDocs(ActionEvent event)
          +public void initialize()
          }

          class taskRef
          {
          +private SimpleStringProperty taskName;
          +private SimpleStringProperty dueDate;
          +private SimpleStringProperty status;

          +public Person(String taskName,  String dueDate, String status )
          +public String getStatus()
          +public void setStatus( String status)
          +public String getDueDate()
          +public void setDueDate(String dueDate)
          +public String getFirstName()
          +public void setFirstName(String taskName)
          +public String toString()
          }

          class sceneController
          {
          +private Stage stage;
          +private Scene scene;
          +private Parent root;

          +public void switchToScene1(ActionEvent event)
          +public void switchToScene2(ActionEvent event)
          }

          class toDoApplication
          {
          +public void start(Stage stage)
          +public static void main(String[] args)
          }tage stage;
+private Scene scene;
+private Parent root;

+public void switchToScene1(ActionEvent event)
+public void switchToScene2(ActionEvent event)
}

class toDoApplication
{
+public void start(Stage stage)
+public static void main(String[] args)
}
@enduml